name: CI – Task API (Build + Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-java:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      - name: Maven build (skip tests & test compile)
        run: mvn -B -Dmaven.test.skip=true clean package


      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-api-jar
          path: target/*.jar
          if-no-files-found: error

  docker-build:
    name: Docker Build (no push)
    needs: build-java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: task-api:ci-test
